[IDENTIFICATION]
# Set your user agent string here.
USERAGENT = IR US26 82006561, 93706229, 80898935, 73572610

[CONNECTION]
HOST = styx.ics.uci.edu
PORT = 9000

[CRAWLER]
SEEDURL = https://ics.uci.edu,https://cs.ics.uci.edu,https://www.informatics.uci.edu,https://informatics.ics.uci.edu,https://stat.ics.uci.edu
# In seconds
POLITENESS = 0.5

[LOCAL PROPERTIES]
# Save file for progress
SAVE = frontier.shelve

# IMPORTANT: DO NOT CHANGE IT IF YOU HAVE NOT IMPLEMENTED MULTITHREADING.
THREADCOUNT = 1

